### ISSUE TITLE
GitHub command suggestion

### ISSUE THREAD

**Issue by StarTwi** [FalseDev/Tech-Struck#5] opened 2021-02-24 13:30 UTC
Make a command to check someone's GitHub stats just like finding a user profile smh and DO NOT FORGET TO INCLUDE THEIR PFP THERE Imao :FalseFacePalmLaugh: <br>

**Comment by FalseDev** [comment] 2021-02-24 13:31
Lmao this is a clone of #4

**Comment by StarTwi** [comment] 2021-02-24 13:33
;-; brb killing the og

**Comment by StarTwi** [comment] 2021-02-24 13:35
![image](https://user-images.githubusercontent.com/71965763/109008362-4142b580-76d3-11eb-93ab-5c81bc64b137.png)
:starlightwtfbro: was just gonna close this one Imao

**Comment by ghost** [comment] 2021-02-25 03:24
> Make a command to check someone's GitHub stats just like finding a user profile smh and DO NOT FORGET TO INCLUDE THEIR PFP THERE Imao :FalseFacePalmLaugh:

bruh ur copy pasting issues to get commits? -_-

**Comment by CodeWithSwastik** [comment] 2021-02-25 05:29
Closing because it is a duplicate of #4

**Closed as completed by CodeWithSwastik** 2021-02-25 05:29 UTC
Labels: duplicate
