### ISSUE TITLE
beer cmd is drunk 

### ISSUE THREAD

**Issue by RakunaM** [FalseDev/Tech-Struck#48] opened 2021-04-09 11:02 UTC
![IMG_20210409_163002.jpg](https://user-images.githubusercontent.com/80162047/114170827-1940a600-9951-11eb-93bf-51a0f6e563fd.jpg) 

add space there

**Comment by FalseDev** [comment] 2021-04-09 11:08
Duplicate of #41, already fixed

**Closed as completed by FalseDev** 2021-04-09 11:08 UTC
